### ISSUE TITLE
Show you guys the default account password.

### ISSUE THREAD

**Issue by coffeehb** [chennqqi/godnslog#1]
admin/password
from webui.go
https://github.com/chennqqi/godnslog/blob/4568cd9904fcfa5dd7fe92e36b607f29de9c61b3/server/webui.go

**Comment by chennqqi** [comment]
Yeah, it's default admin user. Users should change this default password when first run.

**Comment by chennqqi** [comment]
fix this isssue in v0.4.0. Like mysql, godnslog will create a random super admin password when first run. Users can get this from console logs
