### ISSUE TITLE
在反向代理的情景下待优化的功能

### ISSUE THREAD

**Issue by Margular** [chennqqi/godnslog#10]
在反向代理场景下，安全设置中的HTTP地址显示的还是IP地址，但是实际上是访问不到的，因为默认可能不是使用godnslog服务，希望能改为显示域名

另外反向代理场景下域名重绑定功能不能添加IP

**Comment by chennqqi** [comment]
这个地方可以探讨一下，HTTP LOG的目的是DNSLOG无法使用（例如禁止UDP53 出内网）的情况下使用，既然可以使用域名解析（域名转发）那么可以直接使用DNS。参考: [issue 4](https://github.com/chennqqi/godnslog/issues/4)
后端程序处理httplog没有看域名直接按照IP来的，走方向代理也是可以的。

**Comment by Margular** [comment]
dns的使用是有限制的，有时候你就是只能控制URL的某些部分，可能两个功能都能用是最好的

**Comment by chennqqi** [comment]
当前版本是可以支持基于域名的反向代理的，通过nginx转发即可
