### ISSUE TITLE
http log希望能支持对参数的记录

### ISSUE THREAD

**Issue by Margular** [chennqqi/godnslog#11]
即http://x.x.x.x/path/?x=...，对x参数的内容能够记录，参数其实比路径能够记录的信息更加丰富

**Comment by chennqqi** [comment]
@Margular 可否举一个具体的例子啊，我感觉路径已经足够了

**Comment by Margular** [comment]
有时候blind的程序只能注入某个参数，然后你这里只支持注入路径。。

**Comment by chennqqi** [comment]
@Margular 盲注检测一般用load_file等触发DNSLOG来检测，DNSLOG一般使用前缀来传递变量的，SSRF，crlf等可以访问HTTP可以用HTTPLOG来进行检测，此时paylaod是URL，传递变量可以用参数也可以用路径。
