### ISSUE TITLE
HTTP Log建议

### ISSUE THREAD

**Issue by XTeam-Wing** [chennqqi/godnslog#19]
目前http log是一个web路径记录，实际测试的时候没有一个域名方便，可以改成一个单域名。dns和http都能接收。

**Comment by XTeam-Wing** [comment]
可以参考下https://app.interactsh.com/
直接展示原始的请求数据。

**Comment by chennqqi** [comment]
> 

好主意，我参考下。

**Comment by chennqqi** [comment]
> 目前http log是一个web路径记录，实际测试的时候没有一个域名方便，可以改成一个单域名。dns和http都能接收。

用域名是方便，最初也是这样设计的，实际上用HTTP的场景一般是DNS出不来时才用HTTP。

**Comment by XTeam-Wing** [comment]
> > 目前http log是一个web路径记录，实际测试的时候没有一个域名方便，可以改成一个单域名。dns和http都能接收。
> 
> 用域名是方便，最初也是这样设计的，实际上用HTTP的场景一般是DNS出不来时才用HTTP。

这样主要是多了一步测试，正常测试填个域名，dns和http都能通过Web看到，方便很多。
