### ISSUE TITLE
No user 是什么意思？

### ISSUE THREAD

**Issue by lovelyjuice** [chennqqi/godnslog#23]
请求：
```http://xxx.xxx.xxx.141/data/dns?q=1639741859796ypoii&t=1639741863&blur=1&hash=bc4481bd9cd9ce9d706dadf93369e24e```
响应：
```{"message":"No User","code":3,"timestemp":1639741900}```

1639741859796ypoii 这个域名前缀在webui里面是能看到的，但是用api访问就不行，hash参数用文档里面的python算法验证了也没错，secret为```blu35qr51z2jy0zxzoeraj2pl9egy9zb1vc73bjc67sz4ftew44fksxmczb9m4w6```

![image](https://user-images.githubusercontent.com/20644461/146543479-33c30e3a-8b06-452c-bd90-90a96b1da205.png)

**Comment by Phuker** [comment]
作者设计的 API 必须通过系统随机分配的 DNS 域名才能调用，不能通过 IP 访问（否则只有 hash，服务无法确定调用者是哪个账号）

假设系统随机分配的域名为 `qwerty123456.example.com`，你需要把 URL 改为：`http://qwerty123456.example.com/data/dns?q=1639741859796ypoii&t=1639741863&blur=1&hash=bc4481bd9cd9ce9d706dadf93369e24e`

PS. 虽然又不是不能用，但是个人比较喜欢 [ceye.io](http://ceye.io/api) 的 API 风格，每个人调用的都是同一个域名，就一个简单的 token，方便手动修改 URL 参数。目前 godnslog 的 API 缺点很明显，难以理解，调用复杂，必须通过代码调用，无法随意手动修改参数。个人猜测作者设计的这套时间戳 secret 签名机制的目的是防止重放攻击，个人则比较倾向于使用 HTTPS 从根本上保证安全性。

注：我用的是 0.7.0 版本

**Comment by lovelyjuice** [comment]
原来如此，我还是觉得把时间戳限制设为一分钟实在是太短了，vps和客户端过几个月时间就能相差一分钟以上，到时候出现问题又得重新调试找原因。

**Comment by Phuker** [comment]
> 原来如此，我还是觉得把时间戳限制设为一分钟实在是太短了，vps和客户端过几个月时间就能相差一分钟以上，到时候出现问题又得重新调试找原因。

如果设计了防重放的话，这么搞没问题（类似 v2ray），你可能需要配置一下 NTP

**Comment by lovelyjuice** [comment]
> 

tls协议的时间校验都都没它严格，而且对于dnslog这种应用，防重放没有意义
