### ISSUE TITLE
关于HTTP LOG功能建议

### ISSUE THREAD

**Issue by shmilylty** [chennqqi/godnslog#4]
建议使用域名来生成验证URL，而不是直接使用服务器IP地址。

**Comment by chennqqi** [comment]
一开始这么设计的，后来发现需要客户端请求的环境支持DNS解析，这对于漏洞验证的环境要求有点苛刻了(比如说本地DNS不支持外网解析)。既然能用DNS验证那么用DNS验证即可，而使用IP方式可以避免这个问题。

**Comment by shmilylty** [comment]
好的 感谢回复
