### ISSUE TITLE
docker构建失败

### ISSUE THREAD

**Issue by shmilylty** [chennqqi/godnslog#5]
最新的docker构建失败的

![image](https://user-images.githubusercontent.com/24275308/96700596-35ac4e80-13c2-11eb-8263-9a0b5f519319.png)

**Comment by chennqqi** [comment]
0.4.1合并时有点问题，构建显示成功，但是没镜像。
用latest这个tag吧
```
docker run -it -p80:8080 -p53:53/udp "sort/godnslog:latest" serve  -domain yourdomain.com -4 100.100.100.100
```
