### ISSUE TITLE
DNS配置好后，无法解析。

### ISSUE THREAD

**Issue by joke0jie** [chennqqi/godnslog#7]
按你文档中配置好自定义DNS HOST然后运行程序后，无法收到DNS请求。可以的话加个微信请教一下：o0x1024

**Comment by chennqqi** [comment]
用https://lookup.icann.org/lookup 验证一下你DNS配置是否生效。
另外你本地nslookup或者dig一下看是不是你的本地DNS缓存还未刷新

**Comment by joke0jie** [comment]
没事了，我估计是阿里云得实名认证，没成功之前解析不生效，存在延迟的情况 。已经解决了，多谢
