### ISSUE TITLE
dnslog定时清理功能

### ISSUE THREAD

**Issue by RedTeamWing** [chennqqi/godnslog#8]
dnslog定时清理功能可能是为了方便清理，但是遇到延时dnslog就不太方便，现在是2小时自动清理，好像是设置功能更新那里有bug没写好，点击更新服务端502错误。❌

**Comment by chennqqi** [comment]
用线上的版本测试了一下，问题确实存在，稍后修复

**Comment by chennqqi** [comment]
更新语句有个字段写错了，更新了，你试试看
